name: Update FE Container Image in EKS

on:
  push:
    branches:
      - main

jobs:
  update-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      # Builds New Docker Image Locally
      - name: Build Docker Image
        run: | 
          docker build -t nextjs-docker .
          docker tag nextjs-docker:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # Pushes new Docker Image to ECR Repository
      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # Run K8 Manifests
      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/eks-fe eks-fe=ghcr.io/yourusername/eks-fe:latest --record
          kubectl rollout status deployment/eks-fe